# Copyright 2014 Timothy Zhang(zt@live.cn).
#
# This file is part of Structer.
#
# Structer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Structer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Structer.  If not, see <http://www.gnu.org/licenses/>.



# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcFilterEditorDialog(wx.Dialog):
#!XRCED:begin-block:xrcFilterEditorDialog.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcFilterEditorDialog.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "FilterEditorDialog")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_BUTTON, self.OnButton_button_okay, id=xrc.XRCID('button_okay'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_button_cancel, id=xrc.XRCID('button_cancel'))

#!XRCED:begin-block:xrcFilterEditorDialog.OnButton_button_okay
    def OnButton_button_okay(self, evt):
        # Replace with event handler code
        self.EndModal(wx.ID_OK)
#!XRCED:end-block:xrcFilterEditorDialog.OnButton_button_okay        

#!XRCED:begin-block:xrcFilterEditorDialog.OnButton_button_cancel
    def OnButton_button_cancel(self, evt):
        # Replace with event handler code
        self.EndModal(wx.ID_CANCEL)
#!XRCED:end-block:xrcFilterEditorDialog.OnButton_button_cancel        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    filter_editor_xrc = '''\
<?xml version="1.0" ?><resource class="wxPanel">
  <object class="wxDialog" name="FilterEditorDialog">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxPanel">
          <object class="wxBoxSizer">
            <orient>wxHORIZONTAL</orient>
            <object class="spacer">
              <size>5,5</size>
            </object>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <object class="spacer">
                  <size>5,5</size>
                </object>
                <object class="sizeritem">
                  <object class="unknown" name="text_ctrl">
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <option>1</option>
                  <flag>wxALL|wxEXPAND|wxGROW</flag>
                </object>
                <object class="spacer">
                  <size>5,5</size>
                </object>
                <object class="sizeritem">
                  <object class="wxBoxSizer">
                    <object class="spacer">
                      <size>5,5</size>
                    </object>
                    <object class="sizeritem">
                      <object class="wxButton" name="button_okay">
                        <label>&amp;OK</label>
                        <default>1</default>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                        </XRCED>
                      </object>
                    </object>
                    <object class="spacer">
                      <size>5,5</size>
                    </object>
                    <object class="sizeritem">
                      <object class="wxButton" name="button_cancel">
                        <label>&amp;Cancel</label>
                        <XRCED>
                          <events>EVT_BUTTON</events>
                        </XRCED>
                      </object>
                    </object>
                    <object class="spacer">
                      <size>5,5</size>
                    </object>
                    <orient>wxHORIZONTAL</orient>
                  </object>
                  <flag>wxALL|wxALIGN_RIGHT</flag>
                </object>
                <object class="spacer">
                  <size>5,5</size>
                </object>
                <orient>wxVERTICAL</orient>
              </object>
              <option>1</option>
              <flag>wxALL|wxEXPAND|wxGROW</flag>
            </object>
            <object class="spacer">
              <size>5,5</size>
            </object>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND|wxGROW</flag>
        <minsize>640,480</minsize>
      </object>
    </object>
    <centered>1</centered>
    <style>wxBORDER_SIMPLE|wxDEFAULT_DIALOG_STYLE|wxCAPTION</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/filter_editor/filter_editor_xrc', filter_editor_xrc)
    __res.Load('memory:XRC/filter_editor/filter_editor_xrc')

