# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcListToolbar(wx.ToolBar):
    def __init__(self, parent):
        pre = get_resources().LoadToolBar(parent, "ListToolbar")
        self.PostCreate(pre)
        
        # Define variables for the toolbar items
        self.sort_by_name = self.FindById(xrc.XRCID("sort_by_name"))
        self.sort_by_id = self.FindById(xrc.XRCID("sort_by_id"))
        self.sort_by_time = self.FindById(xrc.XRCID("sort_by_time"))
        self.sort_by_type = self.FindById(xrc.XRCID("sort_by_type"))
        self.sort_acsending = self.FindById(xrc.XRCID("sort_acsending"))
        self.sort_descending = self.FindById(xrc.XRCID("sort_descending"))
        self.list_list = self.FindById(xrc.XRCID("list_list"))
        self.list_icon = self.FindById(xrc.XRCID("list_icon"))

        self.Bind(wx.EVT_TOOL, self.OnTool_sort_by_name, self.sort_by_name)
        self.Bind(wx.EVT_UPDATE_UI, self.OnUpdate_ui_sort_by_name, self.sort_by_name)
        self.Bind(wx.EVT_TOOL, self.OnTool_sort_by_id, self.sort_by_id)
        self.Bind(wx.EVT_UPDATE_UI, self.OnUpdate_ui_sort_by_id, self.sort_by_id)
        self.Bind(wx.EVT_TOOL, self.OnTool_sort_by_time, self.sort_by_time)
        self.Bind(wx.EVT_UPDATE_UI, self.OnUpdate_ui_sort_by_time, self.sort_by_time)
        self.Bind(wx.EVT_TOOL, self.OnTool_sort_by_type, self.sort_by_type)
        self.Bind(wx.EVT_UPDATE_UI, self.OnUpdate_ui_sort_by_type, self.sort_by_type)
        self.Bind(wx.EVT_TOOL, self.OnTool_sort_acsending, self.sort_acsending)
        self.Bind(wx.EVT_UPDATE_UI, self.OnUpdate_ui_sort_acsending, self.sort_acsending)
        self.Bind(wx.EVT_TOOL, self.OnTool_sort_descending, self.sort_descending)
        self.Bind(wx.EVT_UPDATE_UI, self.OnUpdate_ui_sort_descending, self.sort_descending)
        self.Bind(wx.EVT_TOOL, self.OnTool_list_list, self.list_list)
        self.Bind(wx.EVT_UPDATE_UI, self.OnUpdate_ui_list_list, self.list_list)
        self.Bind(wx.EVT_TOOL, self.OnTool_list_icon, self.list_icon)
        self.Bind(wx.EVT_UPDATE_UI, self.OnUpdate_ui_list_icon, self.list_icon)

#!XRCED:begin-block:xrcListToolbar.OnTool_sort_by_name
    def OnTool_sort_by_name(self, evt):
        # Replace with event handler code
        self.list.sort_by('name')
#!XRCED:end-block:xrcListToolbar.OnTool_sort_by_name        

#!XRCED:begin-block:xrcListToolbar.OnUpdate_ui_sort_by_name
    def OnUpdate_ui_sort_by_name(self, evt):
        # Replace with event handler code
        evt.Enable(self.list.has_item())
#!XRCED:end-block:xrcListToolbar.OnUpdate_ui_sort_by_name        

#!XRCED:begin-block:xrcListToolbar.OnTool_sort_by_id
    def OnTool_sort_by_id(self, evt):
        # Replace with event handler code
        self.list.sort_by('id')
#!XRCED:end-block:xrcListToolbar.OnTool_sort_by_id        

#!XRCED:begin-block:xrcListToolbar.OnUpdate_ui_sort_by_id
    def OnUpdate_ui_sort_by_id(self, evt):
        # Replace with event handler code
        evt.Enable(self.list.has_item())
#!XRCED:end-block:xrcListToolbar.OnUpdate_ui_sort_by_id        

#!XRCED:begin-block:xrcListToolbar.OnTool_sort_by_time
    def OnTool_sort_by_time(self, evt):
        # Replace with event handler code
        self.list.sort_by('time')
#!XRCED:end-block:xrcListToolbar.OnTool_sort_by_time        

#!XRCED:begin-block:xrcListToolbar.OnUpdate_ui_sort_by_time
    def OnUpdate_ui_sort_by_time(self, evt):
        # Replace with event handler code
        evt.Enable(self.list.has_item())
#!XRCED:end-block:xrcListToolbar.OnUpdate_ui_sort_by_time        

#!XRCED:begin-block:xrcListToolbar.OnTool_sort_by_type
    def OnTool_sort_by_type(self, evt):
        # Replace with event handler code
        self.list.sort_by('type')
#!XRCED:end-block:xrcListToolbar.OnTool_sort_by_type        

#!XRCED:begin-block:xrcListToolbar.OnUpdate_ui_sort_by_type
    def OnUpdate_ui_sort_by_type(self, evt):
        # Replace with event handler code
        evt.Enable(self.list.has_item())
#!XRCED:end-block:xrcListToolbar.OnUpdate_ui_sort_by_type        

#!XRCED:begin-block:xrcListToolbar.OnTool_sort_acsending
    def OnTool_sort_acsending(self, evt):
        # Replace with event handler code
        self.list.sort_by(None, True)
#!XRCED:end-block:xrcListToolbar.OnTool_sort_acsending        

#!XRCED:begin-block:xrcListToolbar.OnUpdate_ui_sort_acsending
    def OnUpdate_ui_sort_acsending(self, evt):
        # Replace with event handler code
        evt.Enable(self.list.has_item())
#!XRCED:end-block:xrcListToolbar.OnUpdate_ui_sort_acsending        

#!XRCED:begin-block:xrcListToolbar.OnTool_sort_descending
    def OnTool_sort_descending(self, evt):
        # Replace with event handler code
        self.list.sort_by(None, False)
#!XRCED:end-block:xrcListToolbar.OnTool_sort_descending        

#!XRCED:begin-block:xrcListToolbar.OnUpdate_ui_sort_descending
    def OnUpdate_ui_sort_descending(self, evt):
        # Replace with event handler code
        evt.Enable(self.list.has_item())
#!XRCED:end-block:xrcListToolbar.OnUpdate_ui_sort_descending        

#!XRCED:begin-block:xrcListToolbar.OnTool_list_list
    def OnTool_list_list(self, evt):
        # Replace with event handler code
        print "OnTool_list_list()"
#!XRCED:end-block:xrcListToolbar.OnTool_list_list        

#!XRCED:begin-block:xrcListToolbar.OnUpdate_ui_list_list
    def OnUpdate_ui_list_list(self, evt):
        # Replace with event handler code
        evt.Enable(False)
#!XRCED:end-block:xrcListToolbar.OnUpdate_ui_list_list        

#!XRCED:begin-block:xrcListToolbar.OnTool_list_icon
    def OnTool_list_icon(self, evt):
        # Replace with event handler code
        print "OnTool_list_icon()"
#!XRCED:end-block:xrcListToolbar.OnTool_list_icon        

#!XRCED:begin-block:xrcListToolbar.OnUpdate_ui_list_icon
    def OnUpdate_ui_list_icon(self, evt):
        # Replace with event handler code
        evt.Enable(False)
#!XRCED:end-block:xrcListToolbar.OnUpdate_ui_list_icon        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    list_toolbar_xrc = '''\
<?xml version="1.0" ?><resource class="tool">
  <object class="wxToolBar" name="ListToolbar">
    <object class="wxStaticText" name="sort_label">
      <label>  Sort  </label>
    </object>
    <object class="tool" name="sort_by_name">
      <bitmap stock_id="wxART_HELP_SETTINGS"/>
      <radio>1</radio>
      <tooltip>Sort by name</tooltip>
      <longhelp>Sort by name</longhelp>
      <label>Sort by name</label>
      <XRCED>
        <events>EVT_TOOL|EVT_UPDATE_UI</events>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="tool" name="sort_by_id">
      <bitmap stock_id="wxART_INFORMATION"/>
      <radio>1</radio>
      <tooltip>Sort by id</tooltip>
      <longhelp>Sort by id</longhelp>
      <label>Sort by id</label>
      <XRCED>
        <events>EVT_TOOL|EVT_UPDATE_UI</events>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="tool" name="sort_by_time">
      <bitmap stock_id="wxART_MISSING_IMAGE"/>
      <radio>1</radio>
      <tooltip>Sort by time</tooltip>
      <longhelp>Sort by time</longhelp>
      <label>Sort by time</label>
      <XRCED>
        <events>EVT_TOOL|EVT_UPDATE_UI</events>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="tool" name="sort_by_type">
      <bitmap stock_id="wxART_MISSING_IMAGE"/>
      <radio>1</radio>
      <tooltip>Sort by type</tooltip>
      <longhelp>Sort by type</longhelp>
      <label>Type</label>
      <XRCED>
        <events>EVT_TOOL|EVT_UPDATE_UI</events>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="separator"/>
    <object class="tool" name="sort_acsending">
      <bitmap stock_id="wxART_GO_UP"/>
      <radio>1</radio>
      <tooltip>Ascending</tooltip>
      <longhelp>Ascending</longhelp>
      <label>Ascending</label>
      <XRCED>
        <events>EVT_TOOL|EVT_UPDATE_UI</events>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="tool" name="sort_descending">
      <bitmap stock_id="wxART_GO_DOWN"/>
      <radio>1</radio>
      <tooltip>Descending</tooltip>
      <longhelp>Descending</longhelp>
      <label>Descending</label>
      <XRCED>
        <events>EVT_TOOL|EVT_UPDATE_UI</events>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="separator"/>
    <object class="tool" name="list_list">
      <bitmap stock_id="wxART_LIST_VIEW"/>
      <radio>1</radio>
      <tooltip>List view</tooltip>
      <longhelp>List view</longhelp>
      <label>List view</label>
      <XRCED>
        <events>EVT_TOOL|EVT_UPDATE_UI</events>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <object class="tool" name="list_icon">
      <bitmap stock_id="wxART_FOLDER"/>
      <radio>1</radio>
      <tooltip>Icon view</tooltip>
      <longhelp>Icon view</longhelp>
      <label>Icon view</label>
      <XRCED>
        <events>EVT_TOOL|EVT_UPDATE_UI</events>
        <assign_var>1</assign_var>
      </XRCED>
    </object>
    <bitmapsize>32,32</bitmapsize>
    <style>wxTB_FLAT</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/list_toolbar/list_toolbar_xrc', list_toolbar_xrc)
    __res.Load('memory:XRC/list_toolbar/list_toolbar_xrc')

