# Copyright 2014 Timothy Zhang(zt@live.cn).
#
# This file is part of Structer.
#
# Structer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Structer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Structer.  If not, see <http://www.gnu.org/licenses/>.



# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcRefDialog(wx.Dialog):
#!XRCED:begin-block:xrcRefDialog.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcRefDialog.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "RefDialog")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.tree_ctrl = xrc.XRCCTRL(self, "tree_ctrl")
        self.text_ctrl = xrc.XRCCTRL(self, "text_ctrl")
        self.grid = xrc.XRCCTRL(self, "grid")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    ref_dialog_xrc = '''\
<?xml version="1.0" ?><resource class="wxDialog">
  <object class="wxDialog" name="RefDialog">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxHORIZONTAL</orient>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="spacer">
                <size>5,5</size>
              </object>
              <object class="sizeritem">
                <object class="wxBoxSizer">
                  <orient>wxHORIZONTAL</orient>
                  <object class="spacer">
                    <size>5,5</size>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTreeCtrl" name="tree_ctrl">
                      <style>wxTR_HIDE_ROOT|wxTR_DEFAULT_STYLE</style>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                    <minsize>150, 300</minsize>
                  </object>
                  <object class="spacer">
                    <size>5,5</size>
                  </object>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="spacer">
                <size>5,5</size>
              </object>
              <label>&amp;Browse</label>
              <orient>wxVERTICAL</orient>
            </object>
            <option>3</option>
            <flag>wxEXPAND</flag>
            <minsize>180,300</minsize>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="spacer">
                <size>0,5</size>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="text_ctrl">
                  <tooltip>Type id, name or pinyin here.</tooltip>
                  <help>Type id, name or pinyin here.</help>
                  <focused>1</focused>
                  <style>wxTE_PROCESS_ENTER</style>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>0</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="spacer">
                <size>0,5</size>
              </object>
              <object class="sizeritem">
                <object class="wxGrid" name="grid">
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="spacer">
                <size>0,5</size>
              </object>
              <label>&amp;Search(By id, name or pinyin)</label>
              <orient>wxVERTICAL</orient>
            </object>
            <option>3</option>
            <flag>wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxPanel"/>
            <option>3</option>
            <flag>wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
        </object>
        <option>1</option>
        <flag>wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxStatusBar" name="status"/>
        <option>0</option>
        <flag>wxEXPAND</flag>
      </object>
    </object>
    <size>800,600</size>
    <title>Choose a reference</title>
    <style>wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxCLOSE_BOX</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/ref_dialog/ref_dialog_xrc', ref_dialog_xrc)
    __res.Load('memory:XRC/ref_dialog/ref_dialog_xrc')

