# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcRefDialog(wx.Dialog):
#!XRCED:begin-block:xrcRefDialog.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcRefDialog.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "RefDialog")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.text_ctrl = xrc.XRCCTRL(self, "text_ctrl")
        self.grid = xrc.XRCCTRL(self, "grid")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    ref_dialog_xrc = '''\
<?xml version="1.0" ?><resource class="wxDialog">
  <object class="wxDialog" name="RefDialog">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxHORIZONTAL</orient>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="spacer">
                <size>0,5</size>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>eg: &quot;123 456; level&gt;10; hp&lt;100&quot;, shows all objects whose name or id contains &quot;123 456&quot; and level&gt;10 and hp&lt;100.\nuse up/down arrow keys to navigate, and enter key to select.</label>
                </object>
              </object>
              <object class="spacer">
                <size>0,5</size>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="text_ctrl">
                  <tooltip>Type id, name or pinyin here.</tooltip>
                  <help>Type id, name or pinyin here.</help>
                  <focused>1</focused>
                  <style>wxTE_PROCESS_ENTER</style>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>0</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="spacer">
                <size>0,5</size>
              </object>
              <object class="sizeritem">
                <object class="wxGrid" name="grid">
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
                <minsize>640,480</minsize>
              </object>
              <object class="spacer">
                <size>0,5</size>
              </object>
              <label>&amp;Search(By id, name or pinyin, and expression)</label>
              <orient>wxVERTICAL</orient>
            </object>
            <option>1</option>
            <flag>wxEXPAND</flag>
            <minsize>800,600</minsize>
          </object>
          <object class="spacer" name="status">
            <size>5,5</size>
          </object>
        </object>
        <option>1</option>
        <flag>wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxStatusBar" name="status"/>
        <option>0</option>
        <flag>wxEXPAND</flag>
      </object>
    </object>
    <size>800,600</size>
    <title>Choose a reference</title>
    <style>wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxCLOSE_BOX</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/ref_dialog/ref_dialog_xrc', ref_dialog_xrc)
    __res.Load('memory:XRC/ref_dialog/ref_dialog_xrc')

